version: '3'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis_cache:
    image: redis:5.0.6
    ports:
      - "6391:6379"
