apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: recipe_box
    component: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: recipe_box
    component: postgres
